release-date = "2021-05-21"

[[entries]]
id = "c23842d4-d6d0-491c-a1e8-4dfd0b0233e9"
type = "improvement"
description = "update type hints, use `@dataclass` over `nr.sumtype` which has MyPy support"
author = "@NiklasRosenstein"

[[entries]]
id = "7fd34d20-3738-413c-8572-0236fa0a34e4"
type = "fix"
description = "fix `discover()` to ignore Python files with more than one dot in it"
author = "@NiklasRosenstein"
