release-date = "2022-02-23"

[[entries]]
id = "da68f360-f675-4f64-bce4-457963de4809"
type = "fix"
description = "strip whitespace around `Class.bases`"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/docspec/pulls/55"
issues = [
    "https://github.com/NiklasRosenstein/docspec/issues/53",
]

[[entries]]
id = "2aa754a8-829e-40b0-947d-ebcb1d72284d"
type = "tests"
description = "add `test_funcdef_7_posonly_args` unit test to test various more combinations of function arguments, including `POSITIONAL_ONLY`)"
authors = [
    "@NiklasRosenstein",
    "@tristanlatr",
]
pr = "https://github.com/NiklasRosenstein/docspec/pulls/58"
issues = [
    "https://github.com/NiklasRosenstein/docspec/issues/57",
]

[[entries]]
id = "baf461c7-737f-4cda-b2fd-1213b7637281"
type = "refactor"
description = "use `nr.util.scanner.Scanner` instead of homebrew `ListScanner` class"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/docspec/pulls/58"

[[entries]]
id = "0338523c-6ec7-42f0-aba6-7cf9266302f0"
type = "fix"
description = "fix parsing of positional only arguments"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/docspec/pulls/58"
issues = [
    "https://github.com/NiklasRosenstein/docspec/issues/57",
]

[[entries]]
id = "043bf8eb-3804-4de2-8d46-ddef40b30c49"
type = "feature"
description = "support PEP 420 namespace packages"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/docspec/pull/62"
issues = [
    "https://github.com/NiklasRosenstein/docspec/issues/54",
]

[[entries]]
id = "f773f5b6-3002-45ad-b784-44aaaeca42ad"
type = "improvement"
description = "support Path where a file system path is expected (e.g. `iter_package_files()`, `load_python_modules()`)"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/docspec/pull/62"
issues = [
    "https://github.com/NiklasRosenstein/docspec/issues/61",
]
