[[entries]]
id = "8628524b-3376-45db-a676-240b00c20d08"
type = "fix"
description = "Swap in `blib2to3` parser (bundled with the `black` package) for the stdlib `lib2to3` module in order to support `match` statements (PEP 634 - Structural Pattern Matching)."
author = "@nrser"
pr = "https://github.com/NiklasRosenstein/docspec/pull/80"
