[[entries]]
id = "8628524b-3376-45db-a676-240b00c20d08"
type = "fix"
description = "Swap in `blib2to3` parser (bundled with the `black` package) for the stdlib `lib2to3` module in order to support `match` statements (PEP 634 - Structural Pattern Matching)."
author = "@nrser"
pr = "https://github.com/NiklasRosenstein/docspec/pull/80"

[[entries]]
id = "1e03c529-5dc3-4d7b-a2d9-827376ddeee9"
type = "improvement"
description = "add back `files` as a keyword-only argument to `load_python_modules()`"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/docspec/issues/75",
]

[[entries]]
id = "9e84cf49-c0a4-4ee9-87d7-379f082a7d46"
type = "tests"
description = "add testcase for #76"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/docspec/issues/76",
]
