[[entries]]
id = "c97dec50-a34b-49ad-9dc5-60b693524c03"
type = "breaking change"
description = "rename `Data` to `Variable`"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/docspec/pull/68"
issues = [
  "https://github.com/NiklasRosenstein/docspec/issues/67"
]
