[[entries]]
id = "0fb0c132-6952-4f06-93a6-c285321e812d"
type = "fix"
description = "update `specification.yml` to show correct types of `Argument.location`, `Decoration.location` and `Module.location`"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/docspec/issues/52",
]
