[[entries]]
id = "e3629fc5-e3e3-4c46-a6ab-d5100aa7f72a"
type = "breaking change"
description = "`Docstring` class no longer inherits from `str` and is no longer frozen"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/docspec/issues/49",
]
