[[entries]]
id = "9079a43e-623e-4c34-86b2-075da533e819"
type = "improvement"
description = "Introduce `HasLocation` base class which now serves as the base for `Docstring`, `Decoration`, `Argument` and `ApiObject`."
author = "@NiklasRosenstein"
