name: docspec
version: 1.0.0
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
license: MIT
description: Docspec is a JSON object specification for representing API documentation
  of programming languages.
requirements:
- python ^3.7
- databind.core ^1.0.0
- databind.json ^1.0.0
dev-requirements:
- types-termcolor
entrypoints:
  console_scripts:
  - docspec = docspec.__main__:main
test-driver:
  type: pytest
typed: true
