name: docspec
version: 1.2.0
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
license: MIT
description: Docspec is a JSON object specification for representing API documentation
  of programming languages.
typed: true
requirements:
- python ^3.7
- databind.core ^1.0.0
- databind.json ^1.0.0
- Deprecated ^1.2.12
test-requirements:
- types-Deprecated
- types-termcolor
- databind.core ^1.2.1
test-drivers:
- type: pytest
- type: mypy
entrypoints:
  console_scripts:
  - docspec = docspec.__main__:main
