name: "docspec-python"
modulename: "docspec_python"
version: "0.2.0"
author: "Niklas Rosenstein <rosensteinniklas@gmail.com>"
license: "MIT"
description: "A parser based on lib2to3 producing docspec data from Python source code."
requirements:
  - python ^3.6
  - dataclasses
  - docspec ~0.2.0
entrypoints:
  console_scripts:
    - docspec-python = docspec_python.__main__:main
typed: true
