
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "docspec-python"
version = "2.2.1"
description = "A parser based on lib2to3 producing docspec data from Python source code."
authors = ["Niklas Rosenstein <rosensteinniklas@gmail.com>"]
license = "MIT"
readme = "readme.md"
homepage = "https://github.com/NiklasRosenstein/docspec/"
packages = [{ include = "docspec_python", from="src" }]

[tool.poetry.dependencies]
python = "^3.8"
docspec = "^2.2.1"
"nr.util" = ">=0.7.0"
black = "^24.4.2"

[tool.poetry.dev-dependencies]
ruff = "*"
mypy = "*"
pytest = "*"
types-Deprecated = "*"

[tool.poetry.scripts]
docspec-python = "docspec_python.__main__:main"

[tool.slap]
typed = true

[tool.slap.test]
check = "slap check"
pytest = "pytest -vv"
mypy = "mypy src/ test --check-untyped-defs"
ruff = "ruff check src/ test/ && ruff format --check src/ test/"

[tool.slap.run]
fmt = "ruff format src/ test/"

[tool.mypy]
python_version = "3.8"
explicit_package_bases = true
mypy_path = ["src"]
namespace_packages = true
pretty = true
show_error_codes = true
show_error_context = true
strict = true
warn_no_return = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = "blib2to3.*"
ignore_missing_imports = true

[tool.ruff]
line-length = 120
