# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push: { branches: [ "develop" ], tags: [ "*" ] }
  pull_request: { branches: [ "develop" ] }

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: mycache

      - run: nix run .#lint
      - run: DOCSPEC_TEST_NO_DEVELOP=true nix run .#test

  # changelog-update:
  #   name: "Insert the Pull Request URL into new changelog entries"
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'pull_request'
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: NiklasRosenstein/slap@gha/changelog/update/v2
  #       with: { version: '*' }

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: mycache

      - run: nix run .#docs
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        if: github.ref == 'refs/heads/develop'
        with: { branch: gh-pages, folder: docs/_site, ssh-key: "${{ secrets.DEPLOY_KEY }}" }
