# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push: { branches: [ "develop" ], tags: [ "*" ] }
  pull_request: { branches: [ "develop" ] }

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.x"]
        project: ["docspec", "docspec-python"]
    steps:
    - uses: actions/checkout@v3
    - uses: NiklasRosenstein/slap@gha/install/v1
    - uses: actions/setup-python@v3
      with: { python-version: "${{ matrix.python-version }}" }
    - run: slap install --only ${{ matrix.project }} --no-venv-check -v
    - run: DOCSPEC_TEST_NO_DEVELOP=true slap test ${{ matrix.project }}

  update-changelogs:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: NiklasRosenstein/slap@gha/changelog/update/v2

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: NiklasRosenstein/slap@gha/install/v1
    - run: slap install --only-extras docs --no-venv-check
    - run: slap run docs:build
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      if: github.ref == 'refs/heads/develop'
      with: { branch: gh-pages, folder: docs/_site, ssh-key: "${{ secrets.DEPLOY_KEY }}" }
