# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.x']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install shut==0.17.4 -q
    - name: Test
      run: TEST_NO_DEVELOP=true shut mono test --isolate
    - name: Verify package metadata
      run: shut mono update --verify

  documentation:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: python -m pip install pydoc-markdown==4.2.0 mkdocs -q
    - name: Generate docs
      run: pydoc-markdown --build --site-dir _html
    - name: Publish docs
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        dir: _html
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
